#WARNING: THIS IS GENERATED CODE GENERATED BY .\generate_proto.py.
#DO NOT TOUCH, RERUN THE GENERATOR.
from .merch_service_pb2 import ShirtDescription, GetShirts_Request, GetShirts_Response, GetRelatedShirts_Request, GetRelatedShirts_Response
from ..base_client import DiscoveryClient, MockService
from .merch_service_pb2_grpc import MerchServiceStub


class MerchService(DiscoveryClient):
    def __init__(self,ip_address=None,port=None,mock=False):
        self.ip_address, self.port, self.mock = ip_address, port, mock
        self._mock_service = MerchService_mock()
    
    def GetShirts(self):
        args = locals()
        del args["self"]
        request = GetShirts_Request(**args)
        stub = self.get_stub("merch_service", "GetShirts", request, MerchServiceStub)
        return stub.GetShirts.future(request)
    
    def GetRelatedShirts(self,id=None):
        args = locals()
        del args["self"]
        request = GetRelatedShirts_Request(**args)
        stub = self.get_stub("merch_service", "GetRelatedShirts", request, MerchServiceStub)
        return stub.GetRelatedShirts.future(request)
#from .test_service_pb2 import IMPORT YOUR MESSAGES HERE

class MerchService_mock(MockService):
    pass
