# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

try:
    import merch_service_pb2 as merch__service__pb2
except:
    from . import merch_service_pb2 as merch__service__pb2


class MerchServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetShirts = channel.unary_unary(
        '/MerchService/GetShirts',
        request_serializer=merch__service__pb2.GetShirts_Request.SerializeToString,
        response_deserializer=merch__service__pb2.GetShirts_Response.FromString,
        )
    self.GetRelatedShirts = channel.unary_unary(
        '/MerchService/GetRelatedShirts',
        request_serializer=merch__service__pb2.GetRelatedShirts_Request.SerializeToString,
        response_deserializer=merch__service__pb2.GetRelatedShirts_Response.FromString,
        )


class MerchServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetShirts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRelatedShirts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MerchServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetShirts': grpc.unary_unary_rpc_method_handler(
          servicer.GetShirts,
          request_deserializer=merch__service__pb2.GetShirts_Request.FromString,
          response_serializer=merch__service__pb2.GetShirts_Response.SerializeToString,
      ),
      'GetRelatedShirts': grpc.unary_unary_rpc_method_handler(
          servicer.GetRelatedShirts,
          request_deserializer=merch__service__pb2.GetRelatedShirts_Request.FromString,
          response_serializer=merch__service__pb2.GetRelatedShirts_Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MerchService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
