#WARNING: THIS IS GENERATED CODE GENERATED BY .\generate_client.py.
#DO NOT TOUCH, RERUN THE GENERATOR.
from .greeting_service_pb2 import Greet_Request, Greet_Response
from ..base_client import DiscoveryClient
from .greeting_service_pb2_grpc import GreetingServiceStub


class GreetingService(DiscoveryClient):
    def __init__(self,ip_address=None,port=None):
        self.ip_address, self.port = ip_address, port
    
    def Greet(self,your_name=None):
        args = locals()
        del args["self"]
        request = Greet_Request(**args)
        stub = self.get_stub("greeting_service", "Greet", request, GreetingServiceStub)
        return stub.Greet.future(request)
