# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeting_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16greeting_service.proto\"\"\n\rGreet_Request\x12\x11\n\tyour_name\x18\x01 \x01(\t\"\"\n\x0eGreet_Response\x12\x10\n\x08greeting\x18\x01 \x01(\t2;\n\x0fGreetingService\x12(\n\x05Greet\x12\x0e.Greet_Request\x1a\x0f.Greet_Responseb\x06proto3')
)




_GREET_REQUEST = _descriptor.Descriptor(
  name='Greet_Request',
  full_name='Greet_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='your_name', full_name='Greet_Request.your_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_GREET_RESPONSE = _descriptor.Descriptor(
  name='Greet_Response',
  full_name='Greet_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='Greet_Response.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Greet_Request'] = _GREET_REQUEST
DESCRIPTOR.message_types_by_name['Greet_Response'] = _GREET_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greet_Request = _reflection.GeneratedProtocolMessageType('Greet_Request', (_message.Message,), dict(
  DESCRIPTOR = _GREET_REQUEST,
  __module__ = 'greeting_service_pb2'
  # @@protoc_insertion_point(class_scope:Greet_Request)
  ))
_sym_db.RegisterMessage(Greet_Request)

Greet_Response = _reflection.GeneratedProtocolMessageType('Greet_Response', (_message.Message,), dict(
  DESCRIPTOR = _GREET_RESPONSE,
  __module__ = 'greeting_service_pb2'
  # @@protoc_insertion_point(class_scope:Greet_Response)
  ))
_sym_db.RegisterMessage(Greet_Response)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class GreetingServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Greet = channel.unary_unary(
          '/GreetingService/Greet',
          request_serializer=Greet_Request.SerializeToString,
          response_deserializer=Greet_Response.FromString,
          )


  class GreetingServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Greet(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_GreetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Greet': grpc.unary_unary_rpc_method_handler(
            servicer.Greet,
            request_deserializer=Greet_Request.FromString,
            response_serializer=Greet_Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'GreetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaGreetingServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Greet(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaGreetingServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Greet(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Greet.future = None


  def beta_create_GreetingService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('GreetingService', 'Greet'): Greet_Request.FromString,
    }
    response_serializers = {
      ('GreetingService', 'Greet'): Greet_Response.SerializeToString,
    }
    method_implementations = {
      ('GreetingService', 'Greet'): face_utilities.unary_unary_inline(servicer.Greet),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_GreetingService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('GreetingService', 'Greet'): Greet_Request.SerializeToString,
    }
    response_deserializers = {
      ('GreetingService', 'Greet'): Greet_Response.FromString,
    }
    cardinalities = {
      'Greet': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'GreetingService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
