# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

try:
    import discovery_service_pb2 as discovery__service__pb2
except:
    from . import discovery_service_pb2 as discovery__service__pb2


class DiscoveryServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/DiscoveryService/Register',
        request_serializer=discovery__service__pb2.Register_Request.SerializeToString,
        response_deserializer=discovery__service__pb2.Register_Response.FromString,
        )
    self.GetServices = channel.unary_unary(
        '/DiscoveryService/GetServices',
        request_serializer=discovery__service__pb2.GetServices_Request.SerializeToString,
        response_deserializer=discovery__service__pb2.GetServices_Response.FromString,
        )


class DiscoveryServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=discovery__service__pb2.Register_Request.FromString,
          response_serializer=discovery__service__pb2.Register_Response.SerializeToString,
      ),
      'GetServices': grpc.unary_unary_rpc_method_handler(
          servicer.GetServices,
          request_deserializer=discovery__service__pb2.GetServices_Request.FromString,
          response_serializer=discovery__service__pb2.GetServices_Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DiscoveryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
