# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discovery_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x64iscovery_service.proto\"\x15\n\x13GetServices_Request\"@\n\x11ServiceDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x03(\t\x12\x0c\n\x04port\x18\x03 \x03(\r\"<\n\x14GetServices_Response\x12$\n\x08services\x18\x01 \x03(\x0b\x32\x12.ServiceDefinition\"G\n\x10Register_Request\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x14\n\x0cservice_name\x18\x03 \x03(\t\"\x13\n\x11Register_Response2\x81\x01\n\x10\x44iscoveryService\x12\x31\n\x08Register\x12\x11.Register_Request\x1a\x12.Register_Response\x12:\n\x0bGetServices\x12\x14.GetServices_Request\x1a\x15.GetServices_Responseb\x06proto3')
)




_GETSERVICES_REQUEST = _descriptor.Descriptor(
  name='GetServices_Request',
  full_name='GetServices_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=48,
)


_SERVICEDEFINITION = _descriptor.Descriptor(
  name='ServiceDefinition',
  full_name='ServiceDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ServiceDefinition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='ServiceDefinition.address', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='ServiceDefinition.port', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=114,
)


_GETSERVICES_RESPONSE = _descriptor.Descriptor(
  name='GetServices_Response',
  full_name='GetServices_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='GetServices_Response.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=176,
)


_REGISTER_REQUEST = _descriptor.Descriptor(
  name='Register_Request',
  full_name='Register_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Register_Request.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Register_Request.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Register_Request.service_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=249,
)


_REGISTER_RESPONSE = _descriptor.Descriptor(
  name='Register_Response',
  full_name='Register_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=270,
)

_GETSERVICES_RESPONSE.fields_by_name['services'].message_type = _SERVICEDEFINITION
DESCRIPTOR.message_types_by_name['GetServices_Request'] = _GETSERVICES_REQUEST
DESCRIPTOR.message_types_by_name['ServiceDefinition'] = _SERVICEDEFINITION
DESCRIPTOR.message_types_by_name['GetServices_Response'] = _GETSERVICES_RESPONSE
DESCRIPTOR.message_types_by_name['Register_Request'] = _REGISTER_REQUEST
DESCRIPTOR.message_types_by_name['Register_Response'] = _REGISTER_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetServices_Request = _reflection.GeneratedProtocolMessageType('GetServices_Request', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVICES_REQUEST,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:GetServices_Request)
  ))
_sym_db.RegisterMessage(GetServices_Request)

ServiceDefinition = _reflection.GeneratedProtocolMessageType('ServiceDefinition', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEDEFINITION,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceDefinition)
  ))
_sym_db.RegisterMessage(ServiceDefinition)

GetServices_Response = _reflection.GeneratedProtocolMessageType('GetServices_Response', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVICES_RESPONSE,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:GetServices_Response)
  ))
_sym_db.RegisterMessage(GetServices_Response)

Register_Request = _reflection.GeneratedProtocolMessageType('Register_Request', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_REQUEST,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:Register_Request)
  ))
_sym_db.RegisterMessage(Register_Request)

Register_Response = _reflection.GeneratedProtocolMessageType('Register_Response', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_RESPONSE,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:Register_Response)
  ))
_sym_db.RegisterMessage(Register_Response)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class DiscoveryServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Register = channel.unary_unary(
          '/DiscoveryService/Register',
          request_serializer=Register_Request.SerializeToString,
          response_deserializer=Register_Response.FromString,
          )
      self.GetServices = channel.unary_unary(
          '/DiscoveryService/GetServices',
          request_serializer=GetServices_Request.SerializeToString,
          response_deserializer=GetServices_Response.FromString,
          )


  class DiscoveryServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Register(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetServices(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Register': grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=Register_Request.FromString,
            response_serializer=Register_Response.SerializeToString,
        ),
        'GetServices': grpc.unary_unary_rpc_method_handler(
            servicer.GetServices,
            request_deserializer=GetServices_Request.FromString,
            response_serializer=GetServices_Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDiscoveryServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Register(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetServices(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDiscoveryServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Register(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Register.future = None
    def GetServices(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetServices.future = None


  def beta_create_DiscoveryService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('DiscoveryService', 'GetServices'): GetServices_Request.FromString,
      ('DiscoveryService', 'Register'): Register_Request.FromString,
    }
    response_serializers = {
      ('DiscoveryService', 'GetServices'): GetServices_Response.SerializeToString,
      ('DiscoveryService', 'Register'): Register_Response.SerializeToString,
    }
    method_implementations = {
      ('DiscoveryService', 'GetServices'): face_utilities.unary_unary_inline(servicer.GetServices),
      ('DiscoveryService', 'Register'): face_utilities.unary_unary_inline(servicer.Register),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_DiscoveryService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('DiscoveryService', 'GetServices'): GetServices_Request.SerializeToString,
      ('DiscoveryService', 'Register'): Register_Request.SerializeToString,
    }
    response_deserializers = {
      ('DiscoveryService', 'GetServices'): GetServices_Response.FromString,
      ('DiscoveryService', 'Register'): Register_Response.FromString,
    }
    cardinalities = {
      'GetServices': cardinality.Cardinality.UNARY_UNARY,
      'Register': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'DiscoveryService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
