# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discovery_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x64iscovery_service.proto\"\x15\n\x13GetServices_Request\"@\n\x11ServiceDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x03(\t\x12\x0c\n\x04port\x18\x03 \x03(\r\"<\n\x14GetServices_Response\x12$\n\x08services\x18\x01 \x03(\x0b\x32\x12.ServiceDefinition\"G\n\x10Register_Request\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x14\n\x0cservice_name\x18\x03 \x03(\t\"\x13\n\x11Register_Response2\x81\x01\n\x10\x44iscoveryService\x12\x31\n\x08Register\x12\x11.Register_Request\x1a\x12.Register_Response\x12:\n\x0bGetServices\x12\x14.GetServices_Request\x1a\x15.GetServices_Responseb\x06proto3')
)




_GETSERVICES_REQUEST = _descriptor.Descriptor(
  name='GetServices_Request',
  full_name='GetServices_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=48,
)


_SERVICEDEFINITION = _descriptor.Descriptor(
  name='ServiceDefinition',
  full_name='ServiceDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ServiceDefinition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ServiceDefinition.address', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ServiceDefinition.port', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=114,
)


_GETSERVICES_RESPONSE = _descriptor.Descriptor(
  name='GetServices_Response',
  full_name='GetServices_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='GetServices_Response.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=176,
)


_REGISTER_REQUEST = _descriptor.Descriptor(
  name='Register_Request',
  full_name='Register_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Register_Request.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Register_Request.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Register_Request.service_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=249,
)


_REGISTER_RESPONSE = _descriptor.Descriptor(
  name='Register_Response',
  full_name='Register_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=270,
)

_GETSERVICES_RESPONSE.fields_by_name['services'].message_type = _SERVICEDEFINITION
DESCRIPTOR.message_types_by_name['GetServices_Request'] = _GETSERVICES_REQUEST
DESCRIPTOR.message_types_by_name['ServiceDefinition'] = _SERVICEDEFINITION
DESCRIPTOR.message_types_by_name['GetServices_Response'] = _GETSERVICES_RESPONSE
DESCRIPTOR.message_types_by_name['Register_Request'] = _REGISTER_REQUEST
DESCRIPTOR.message_types_by_name['Register_Response'] = _REGISTER_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetServices_Request = _reflection.GeneratedProtocolMessageType('GetServices_Request', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVICES_REQUEST,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:GetServices_Request)
  ))
_sym_db.RegisterMessage(GetServices_Request)

ServiceDefinition = _reflection.GeneratedProtocolMessageType('ServiceDefinition', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEDEFINITION,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:ServiceDefinition)
  ))
_sym_db.RegisterMessage(ServiceDefinition)

GetServices_Response = _reflection.GeneratedProtocolMessageType('GetServices_Response', (_message.Message,), dict(
  DESCRIPTOR = _GETSERVICES_RESPONSE,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:GetServices_Response)
  ))
_sym_db.RegisterMessage(GetServices_Response)

Register_Request = _reflection.GeneratedProtocolMessageType('Register_Request', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_REQUEST,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:Register_Request)
  ))
_sym_db.RegisterMessage(Register_Request)

Register_Response = _reflection.GeneratedProtocolMessageType('Register_Response', (_message.Message,), dict(
  DESCRIPTOR = _REGISTER_RESPONSE,
  __module__ = 'discovery_service_pb2'
  # @@protoc_insertion_point(class_scope:Register_Response)
  ))
_sym_db.RegisterMessage(Register_Response)



_DISCOVERYSERVICE = _descriptor.ServiceDescriptor(
  name='DiscoveryService',
  full_name='DiscoveryService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=273,
  serialized_end=402,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='DiscoveryService.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTER_REQUEST,
    output_type=_REGISTER_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetServices',
    full_name='DiscoveryService.GetServices',
    index=1,
    containing_service=None,
    input_type=_GETSERVICES_REQUEST,
    output_type=_GETSERVICES_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOVERYSERVICE)

DESCRIPTOR.services_by_name['DiscoveryService'] = _DISCOVERYSERVICE

# @@protoc_insertion_point(module_scope)
