#WARNING: THIS IS GENERATED CODE GENERATED BY .\generate_client.py.
#DO NOT TOUCH, RERUN THE GENERATOR.
from .pokedex_service_pb2 import GetPokemon_Request, PokemonDescription, GetPokemon_Response
from ..base_client import DiscoveryClient
from .pokedex_service_pb2_grpc import PokedexServiceStub


class PokedexService(DiscoveryClient):
    def __init__(self,ip_address=None,port=None):
        self.ip_address, self.port = ip_address, port
    
    def GetPokemon(self,number=None):
        args = locals()
        del args["self"]
        request = GetPokemon_Request(**args)
        stub = self.get_stub("pokedex_service", "GetPokemon", request, PokedexServiceStub)
        return stub.GetPokemon.future(request)
