# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokedex_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pokedex_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15pokedex_service.proto\"$\n\x12GetPokemon_Request\x12\x0e\n\x06number\x18\x01 \x01(\r\"F\n\x12PokemonDescription\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nevolutions\x18\x03 \x03(\r\"@\n\x13GetPokemon_Response\x12)\n\x0c\x64\x65scriptions\x18\x01 \x03(\x0b\x32\x13.PokemonDescription2I\n\x0ePokedexService\x12\x37\n\nGetPokemon\x12\x13.GetPokemon_Request\x1a\x14.GetPokemon_Responseb\x06proto3')
)




_GETPOKEMON_REQUEST = _descriptor.Descriptor(
  name='GetPokemon_Request',
  full_name='GetPokemon_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='GetPokemon_Request.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=61,
)


_POKEMONDESCRIPTION = _descriptor.Descriptor(
  name='PokemonDescription',
  full_name='PokemonDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='PokemonDescription.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='PokemonDescription.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evolutions', full_name='PokemonDescription.evolutions', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=133,
)


_GETPOKEMON_RESPONSE = _descriptor.Descriptor(
  name='GetPokemon_Response',
  full_name='GetPokemon_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptions', full_name='GetPokemon_Response.descriptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=199,
)

_GETPOKEMON_RESPONSE.fields_by_name['descriptions'].message_type = _POKEMONDESCRIPTION
DESCRIPTOR.message_types_by_name['GetPokemon_Request'] = _GETPOKEMON_REQUEST
DESCRIPTOR.message_types_by_name['PokemonDescription'] = _POKEMONDESCRIPTION
DESCRIPTOR.message_types_by_name['GetPokemon_Response'] = _GETPOKEMON_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPokemon_Request = _reflection.GeneratedProtocolMessageType('GetPokemon_Request', (_message.Message,), dict(
  DESCRIPTOR = _GETPOKEMON_REQUEST,
  __module__ = 'pokedex_service_pb2'
  # @@protoc_insertion_point(class_scope:GetPokemon_Request)
  ))
_sym_db.RegisterMessage(GetPokemon_Request)

PokemonDescription = _reflection.GeneratedProtocolMessageType('PokemonDescription', (_message.Message,), dict(
  DESCRIPTOR = _POKEMONDESCRIPTION,
  __module__ = 'pokedex_service_pb2'
  # @@protoc_insertion_point(class_scope:PokemonDescription)
  ))
_sym_db.RegisterMessage(PokemonDescription)

GetPokemon_Response = _reflection.GeneratedProtocolMessageType('GetPokemon_Response', (_message.Message,), dict(
  DESCRIPTOR = _GETPOKEMON_RESPONSE,
  __module__ = 'pokedex_service_pb2'
  # @@protoc_insertion_point(class_scope:GetPokemon_Response)
  ))
_sym_db.RegisterMessage(GetPokemon_Response)



_POKEDEXSERVICE = _descriptor.ServiceDescriptor(
  name='PokedexService',
  full_name='PokedexService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=201,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPokemon',
    full_name='PokedexService.GetPokemon',
    index=0,
    containing_service=None,
    input_type=_GETPOKEMON_REQUEST,
    output_type=_GETPOKEMON_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POKEDEXSERVICE)

DESCRIPTOR.services_by_name['PokedexService'] = _POKEDEXSERVICE

# @@protoc_insertion_point(module_scope)
